trigger:
- main

pool:
  name: 'Default'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: Compile
    steps:
    # We are using a script instead of the Maven task to force it to work
    - script: |
        "C:\Program Files\apache-maven-3.9.12\bin\mvn.cmd" clean package -DskipTests
      displayName: 'Compile Java Project'
      workingDirectory: '$(Build.SourcesDirectory)'

- stage: Deliver
  displayName: 'Deliver Stage'
  dependsOn: Build
  jobs:
  - job: Publish
    steps:
    - script: echo "Generating Java .jar artifact..."

- stage: Deploy_Dev
  displayName: 'Deploy to Dev'
  dependsOn: Deliver
  jobs:
  - deployment: Dev
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Launching Spring Boot App in Dev..."
